spring:
  application:
    name: dining-order-api

  datasource:
    url: jdbc:mysql://localhost:3306/dining_orderdb?createDatabaseIfNotExist=true
    username: root
    password: SUNDAR

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


